# This is the configuration file for Icinga for Kubernetes.

# Connection configuration for the database to which Icinga for Kubernetes synchronizes data.
# This is also the database used in Icinga for Kubernetes Web to view and work with the data.
database:
  # Database type. Only 'mysql' is supported yet which is the default.
#  type: mysql

  # Database host or absolute Unix socket path.
  host: localhost

  # Database port. By default, the MySQL port.
#  port:

  # Database name.
  database: kubernetes

  # Database user.
  user: kubernetes

  # Database password.
  password: CHANGEME

# Configuration for Prometheus metrics API.
prometheus:
  # Prometheus server URL.
#  url: http://localhost:9090

# Configuration for Icinga Notifications daemon.
notifications:
  # Icinga Notifications daemon base URL.
  # If not set, Icinga for Kubernetes won't send any event to Icinga Notifications (disabled).
#  url: http://localhost:5680

  # The base URL of your Icinga for Kubernetes web module to be used for the generated Icinga Notifications events.
#  kubernetes_web_url: http://localhost/icingaweb2/kubernetes

  # The Icinga for Kubernetes source username used to authenticate in Icinga Notifications.
  # Leave it empty to let Icinga for Kubernetes generate the credentials automatically.
#  username: kubernetes

  # The Icinga for Kubernetes source password used to authenticate in Icinga Notifications.
  # Leave it empty to let Icinga for Kubernetes generate the credentials automatically.
#  password: 0bcf3398-12c8-4cb5-849d-81dcd0644cc7
