apiVersion: v1
kind: Namespace
metadata:
  name: icinga-kubernetes
  labels:
    app: icinga-kubernetes

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icinga-kubernetes-config
  namespace: icinga-kubernetes
data:
  config: |
    # This is the configuration file for Icinga Kubernetes.
    #
    # Connection configuration for the database to which Icinga Kubernetes synchronizes Kubernetes data.
    # This is also the database used in Icinga Kubernetes Web to view and work with the data.
    database:
      # Database type. Either 'mysql' for MySQL or 'pgsql' for PostgreSQL.
      # Defaults to 'mysql'.
    #  type: mysql

      # Database host or absolute Unix socket path.
      host: 10.96.0.2
    
      # Database port. By default, the MySQL or PostgreSQL port, depending on the database type.
    #  port:
    
      # Database name.
      database: kubernetes
    
      # Database user.
      user: kubernetes
    
      # Database password.
      password: kubernetes
    
    # Icinga Kubernetes logs its activities at various severity levels and any errors that occur either
    # on the console or in systemd's journal. The latter is used automatically when running under systemd.
    # In any case, the default log level is 'info'.
    logging:
      # Default logging level. Can be set to 'fatal', 'error', 'warn', 'info' or 'debug'.
      # If not set, defaults to 'info'.
      level: info
    
      # Logging output. Can be set to 'console' (stderr) or 'systemd-journald'.
      # If not set, logs to systemd-journald when running under systemd, otherwise stderr.
    #  output:

      # Interval for periodic logging defined as duration string.
      # A duration string is a sequence of decimal numbers and a unit suffix, such as "20s".
      # Valid units are "ms", "s", "m", "h".
      # Defaults to "20s".
    #  interval: 20s

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icinga-kubernetes
  namespace: icinga-kubernetes

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: icinga-kubernetes
  name: resource-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "get", "watch", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-resources
  namespace: icinga-kubernetes
subjects:
  - kind: ServiceAccount
    name: icinga-kubernetes
    namespace: icinga-kubernetes
roleRef:
  kind: ClusterRole
  name: resource-reader
  apiGroup: "rbac.authorization.k8s.io"

---
apiVersion: v1
kind: Pod
metadata:
  name: icinga-kubernetes
  labels:
    app: icinga-kubernetes
  namespace: icinga-kubernetes
spec:
  serviceAccountName: icinga-kubernetes
  containers:
    - name: icinga-kubernetes
      image: icinga-kubernetes
      imagePullPolicy: Never
      env:
        - name: ICINGA_KUBERNETES_CONFIG
          valueFrom:
            configMapKeyRef:
              name: icinga-kubernetes-config
              key: config
