---
apiVersion: v1
kind: Service
metadata:
  name: icinga-kubernetes
  labels:
    app: icinga-kubernetes
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: icinga-kubernetes
